from aqt import mw

nhknews_model_data = {'id': 1637836984933, 'name': 'nhknews', 'type': 0, 'mod': 1654553802, 'usn': 7941, 'sortf': 0,
                      'did': 1595922742484, 'tmpls': [{'name': 'Card 1', 'ord': 0,
                                                       'qfmt': '<div class="section front">\n<div class="title">Front</div>\n\n<div class="hint" id="hint">\n<p>NHK新聞</p>\n<p>聞き取り練習</p>\n</div>\n<div class="jp" id="mask"></div>\n\n{{Pronunciation}}\n\n</div>\n<!--\n<script type="text/javascript">\n    var mark = \'▢\';\n\t\t var n = Math.floor(Math.random() * 2) + 1;\n    var jp_reg = /[\\w\\u3040-\\u309f\\u30a0-\\u30ff\\u4e00-\\u9faf]/;\n    var ascii_reg = /[^\\u0000-\\u00FF]/;\n\n    function changeText(jp_text, offset, cycle) {\n        var text_length = jp_text.length;\n        var result0 = "";\n        offset = offset % cycle;\n        for (var i = 0; i < text_length; i++) {\n\t\t\t\t\t\t\t//var offset = Math.floor(Math.random() * 6) + 3;\n            var ch = jp_text.charAt(i);\n            if ((i + offset) % cycle && jp_reg.test(ch) && ascii_reg.test(ch)) {\n                result0 += mark;\n            } else {\n                result0 += jp_text.charAt(i);\n            }\n        }\n        return result0;\n    }\n\t\t\n    var orgin = document.getElementById(\'jp\').innerHTML;\n    var mask = document.getElementById(\'mask\');\n\n    // 固定屏蔽第 1/3/5/7....\n\t\n    mask.innerHTML = changeText(orgin, n, 2);\n    // n=2 个汉字随机屏蔽一个\n    //var cycle = 2;\n    //mask.innerHTML = changeText(orgin, Math.ceil(cycle * Math.random(cycle)), cycle);\n</script>\n-->',
                                                       'afmt': '<div class="section back">\n<div class="title">Back</div>\n<div class="contents">\n<table id = "newstext">\n</table>\n\n<jp id="jptext">{{Japanese}}</jp>\n<cn id="cntext">{{Chinese}}</cn>\n\n<script type="text/javascript">\n\n\tvar i=0;\n\tvar jpbox=document.getElementById(\'jptext\').innerHTML;\n\tvar cnbox=document.getElementById(\'cntext\').innerHTML;\n\tvar jparray=jpbox.split("</p>");\n\tvar cnarray=cnbox.split("</p>");\n\n\tfor (i;i<(jparray.length-1);i++)\n\t\t{\n\t\t\tvar tablebox=document.getElementById(\'newstext\');\n\t\t\tvar trobj=document.createElement(\'tr\');\n\t\t\ttrobj.setAttribute("id", "tr"+i);\n\t\t\ttablebox.appendChild(trobj);\n\n\t\t\tvar trxbox=document.getElementById(\'tr\'+i);\n\t\t\tvar tdobj=document.createElement(\'td\');\n\t\t\ttdobj.className="jp";\n\t\t\ttdobj.innerHTML=jparray[i];\n\t\t\ttrxbox.appendChild(tdobj);\n\t\t\tvar trxbox=document.getElementById(\'tr\'+i);\n\t\t\tvar tdobj=document.createElement(\'td\');\n\t\t\ttdobj.className="cn";\n\t\t\ttdobj.innerHTML=cnarray[i];\n\t\t\ttrxbox.appendChild(tdobj);\n\t\t}\n</script>\n<div class="sound">{{Pronunciation}}</div>\n</div>',
                                                       'bqfmt': '', 'bafmt': '', 'did': None, 'bfont': '', 'bsize': 0}],
                      'flds': [
                          {'name': 'Japanese', 'ord': 0, 'sticky': False, 'rtl': False, 'font': 'Arial', 'size': 20,
                           'description': '', 'media': []},
                          {'name': 'Pronunciation', 'ord': 1, 'sticky': False, 'rtl': False, 'font': 'Arial',
                           'size': 20, 'description': '', 'media': []},
                          {'name': 'Chinese', 'ord': 2, 'sticky': False, 'rtl': False, 'font': 'Arial', 'size': 20,
                           'description': '', 'media': []},
                          {'name': 'PageUrl', 'ord': 3, 'sticky': False, 'rtl': False, 'font': 'Arial', 'size': 20,
                           'description': '', 'media': []},
                          {'name': 'AudioUrl', 'ord': 4, 'sticky': False, 'rtl': False, 'font': 'Arial', 'size': 20,
                           'description': '', 'media': []}
                      ],
                      'css': '/*\n正面挖空的代码来自pdawiki论坛，我做了一些修改，但是目前禁用的\n反面的JS代码用来生成双语对齐的效果，来自freemdict论坛的kicbli，致谢!\nNHK新闻的内容来自初心日语同盟微信公众号，非常感谢\nContact: dax26d@gmail.com\n*/\n\n/* 卡片全局设置 */\n.card {\n  font-family      : PingFang, helvetica, arial, sans-serif; \n  font-size        : 14px;\n  text-align       : left;\n  color            : white;\n  background       : #eeeeee;\n  margin           : 0px;\n\theight\t\t\t\t\t\t : 100%;\n}\n\n\n\n/*背面卡片的首字母放大*/\n.back p::first-letter{\n\tfont-size: 24px;\n}\n\n\n/* 日文部分的字体大小设置，以及离边框都空一个字符 */\n.jp{\npadding: 0em 1em;\nfont-size: 18px;\nflex-basis: 100%;\ncolor: #307F9C\t;\n\n}\n\n/* 卡片正面的排版设置 */\n.hint {\n\tdisplay: flex;\n\tflex-direction: column;\n\tjustify-content: center;\n\talign-items: center;\n\tfont-size: 48px;\n\theight: 90vh;\n}\n\n.mobile .hint {\n    height:  70vh;\n}\n\n/* 去除卡片正面的段首缩进 */\n.hint p{\n\ttext-indent: 0;\n}\n\n/* 卡片背面的日文部分第一个字符的颜色设置 */\n.back .jp p::first-letter{\n\tcolor: #EC9A29;\n}\n\n\n/* 卡片背面的中文部分每个字符的颜色设置 */\n.back .cn p::first-letter{\n\tcolor: #EC9A29;\n}\n\n/* 行缩进2个字符 */\np{\ntext-indent: 2em;\n}\n\n\n/* 中文部分的颜色，边距，字体大小设置 */\n.cn {\n\tcolor: #307F9C;\n\tpadding: 0em 1em;\n\tfont-size: 18px;\n\tflex-basis: 100%;\n}\n\n/* 日文和中文并列排布 */\n.contents {\n\tdisplay: inline-flex;\n\theight: 100%;\n\n}\n\n\n\n.section {\n  background-color : #A3F4F5; \n  border-radius    : 10px;\n\tborder\t\t\t\t\t\t : solid 1px #0F8B8D;\n  margin           : 8px 8px;\n  min-height: 98vh;\n  overflow: auto;\n}\n\n.mobile .section {\n  min-height: 77vh;\n}\n\n/* 最上方的横条设置 */\n.title{\n  display          : block;\n  padding          : 5px 12px;\n\tcolor\t\t\t\t\t\t\t : white;\n\tbackground-color : #0F8B8D;\n}\n\n\n/* 水平分割线设置 */\nhr{\n  border     : solid #00adb5 12px;\n\tmargin: 0px;\n\tlength: 100%;\n}\n\n/* 以下部分用来设置由JS代码生成的表格 */\n/* 隐藏中日原文 */\n#jptext {\n  display:none;\n}\n\n#cntext {\n  display:none;\n}\n/* 设置为左右同等宽度，文字在表格中竖向向上对齐 */\ntable{\n    width: 100%;\n}\n\ntd{\n\t\tvertical-align: top;\n    width: 50%;\n}\n\n',
                      'latexPre': '\\documentclass[12pt]{article}\n\\special{papersize=3in,5in}\n\\usepackage[utf8]{inputenc}\n\\usepackage{amssymb,amsmath}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0in}\n\\begin{document}\n',
                      'latexPost': '\\end{document}', 'latexsvg': False, 'req': [[0, 'any', [1]]], 'vers': [],
                      'tags': []}


def add_nhknews_model(col):
    m = mw.col.models.new('nhknews')
    m['tmpls'] = nhknews_model_data['tmpls']
    m['flds'] = nhknews_model_data['flds']
    m['css'] = nhknews_model_data['css']
    col.models.save(m)
